### ISSUE TITLE
Error while scouting

### ISSUE THREAD

**Issue by DeadlyVirez** [ccxt/binance-trade-bot#146]
There seems to be a scouting error with the newest commits, but after the error the bot sometimes keeps on trading

> 2021-02-27 15:30:56,543 - crypto_trader_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
>urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/app/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "crypto_trading.py", line 145, in scout
    all_tickers = client.get_all_market_tickers()
  File "/app/binance_api_manager.py", line 18, in get_all_market_tickers
    return self.BinanceClient.get_all_tickers()
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 437, in get_all_tickers
    return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
>requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

>2021-02-27 15:31:25,134 - crypto_trader_logger - INFO - Will be jumping from <BTT> to XLM
2021-02-27 15:31:26,677 - crypto_trader_logger - INFO - Selling 378547.0 of BTT
2021-02-27 15:31:27,181 - crypto_trader_logger - INFO - Balance is 378547.0
2021-02-27 15:31:27,433 - crypto_trader_logger - INFO - order

**Comment by ardgraft** [comment]
I concur, I have the same issue.

2021-02-27 15:22:29,030 - crypto_trader_logger - INFO - Started
2021-02-27 15:22:29,376 - crypto_trader_logger - INFO - Creating database schema if it doesn't already exist
2021-02-27 15:31:31,809 - crypto_trader_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\python\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\python\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "D:\python\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\python\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\python\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\python\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\python\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\python\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\python\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "D:\python\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\python\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\python\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dropbox\development\python\binance-trade-bot\scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "D:\python\lib\site-packages\schedule\__init__.py", line 147, in _run_job
    ret = job.run()
  File "D:\python\lib\site-packages\schedule\__init__.py", line 491, in run
    ret = self.job_func()
  File "crypto_trading.py", line 145, in scout
    all_tickers = client.get_all_market_tickers()
  File "D:\Dropbox\development\python\binance-trade-bot\binance_api_manager.py", line 18, in get_all_market_tickers
    return self.BinanceClient.get_all_tickers()
  File "D:\python\lib\site-packages\binance\client.py", line 437, in get_all_tickers
    return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
  File "D:\python\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "D:\python\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "D:\python\lib\site-packages\binance\client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by ardgraft** [comment]
I note however that even thought this error is displayed, the flow/main loop resumes. If I CTRL-C the code execution its within the main loop -

Traceback (most recent call last):
  File "crypto_trading.py", line 278, in <module>
    main()
  File "crypto_trading.py", line 274, in main
    time.sleep(1)
KeyboardInterrupt

**Comment by DeadlyVirez** [comment]
@ardgraft yes it keeps working, for me too

**Comment by rel-s** [comment]
Errors of this type are not bugs - they are connection problems, either due to your own internet connection, issues with reaching Binance servers or Binance server downtime. The bot displays these exceptions, but keeps trying to connect, so there isn't any actual bug here. We can continue this discussion on the Discord channel.

**Comment by DeadlyVirez** [comment]
That's good to know!
