### ISSUE TITLE
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time. 

### ISSUE THREAD

**Issue by ghost** [ccxt/binance-trade-bot#164]
Have had this error since the start, buys and sells, but if it get stuck on a coin for over a hour or 2 when it goes back to sell it this happens.  Syncing with internet time does nothing.

```
binance_trader | 2021-03-02 08:25:01,528 - crypto_trader_logger - ERROR - Error while updating value history...

binance_trader | Traceback (most recent call last):

binance_trader | File "/app/scheduler.py", line 25, in _run_job

binance_trader | super()._run_job(job)

binance_trader | File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job

binance_trader | ret = job.run()

binance_trader | File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run

binance_trader | ret = self.job_func()

binance_trader | File "crypto_trading.py", line 193, in update_values

binance_trader | balance = client.get_currency_balance(coin.symbol)

binance_trader | File "/app/binance_api_manager.py", line 36, in get_currency_balance

binance_trader | for currency_balance in self.BinanceClient.get_account()[u"balances"]:

binance_trader | File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 1767, in get_account

binance_trader | return self._get('account', True, data=params)

binance_trader | File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 237, in _get

binance_trader | return self._request_api('get', path, signed, version, **kwargs)

binance_trader | File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api

binance_trader | return self._request(method, uri, signed, **kwargs)

binance_trader | File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 197, in _request

binance_trader | return self._handle_response()

binance_trader | File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response

binance_trader | raise BinanceAPIException(self.response)

binance_trader | binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

binance_trader |

binance_trader | 2021-03-02 08:25:02,712 - crypto_trader_logger - ERROR - Error while updating value history...

binance_trader | Traceback (most recent call last):

binance_trader | File "/app/scheduler.py", line 25, in _run_job

binance_trader | super()._run_job(job)

binance_trader | File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job

binance_trader | ret = job.run()
```

**Comment by ghost** [comment]
this bot should be hitting the /v3/time endpoint when it starts and uses the server time to offset the local time to prevent this

**Comment by ghost** [comment]
I have downloaded a program to update my system time every 10 minutes and it looks like this error is gone. No error in the past two days, previously it was only update once or twice a day.
