### ISSUE TITLE
fees error

### ISSUE THREAD

**Issue by TonyStark** [ccxt/binance-trade-bot#216]
```
2021-03-18 21:51:15,584 - crypto_trading_logger - ERROR - Error while scouting...ent coin: ETHUSDT 
Traceback (most recent call last):
  File "/home/champion/learn/binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/home/champion/.local/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/home/champion/.local/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/home/champion/learn/binance-trade-bot/binance_trade_bot/auto_trader.py", line 155, in scout
    transaction_fee = self.manager.get_fee(pair.from_coin, self.config.BRIDGE, True) + self.manager.get_fee(
  File "/home/champion/learn/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 35, in get_fee
    base_fee = self.get_trade_fees()[origin_coin + target_coin]
  File "/home/champion/.local/lib/python3.8/site-packages/cachetools/decorators.py", line 22, in wrapper
    v = func(*args, **kwargs)
  File "/home/champion/learn/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 28, in get_trade_fees
    return {ticker["symbol"]: ticker["taker"] for ticker in self.binance_client.get_trade_fee()["tradeFee"]}
  File "/home/champion/.local/lib/python3.8/site-packages/binance/client.py", line 2169, in get_trade_fee
    if not res['success']:
KeyError: 'success'
```
Im on latest master

**Comment by TonyStark** [comment]
Okay
I followed this PR to solve issue >> https://github.com/edeng23/binance-trade-bot/pull/208
