### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by varna9000** [ccxt/binance-trade-bot#222]
Hi, I've installed the bot on a Raspberry Pi and left it running overnight. I got the following errors (which it recovered from because I set it up as Systemd service). Is this just a connection error or something else? I suppose the exception could be handled somehow?

```
Error while scouting...
Traceback (most recent call last):
 File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
   chunked=chunked,
 File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
   six.raise_from(e, None)
 File "<string>", line 3, in raise_from
 File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
   httplib_response = conn.getresponse()
 File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
   response.begin()
 File "/usr/lib/python3.7/http/client.py", line 306, in begin
   version, status, reason = self._read_status()
 File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
   line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
 File "/usr/lib/python3.7/socket.py", line 589, in readinto
   return self._sock.recv_into(b)
 File "/home/pi/.local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 328, in recv_into
   return self.recv_into(*args, **kwargs)
 File "/home/pi/.local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
   raise SocketError(str(e))
OSError: (104, 'ECONNRESET')
```

**Comment by rel-s** [comment]
This is not a bug in the bot, but rather a network error on your end. If this issue persists, please reopen it on our Discord channel. Thanks!
