### ISSUE TITLE
Error while scouting

### ISSUE THREAD

**Issue by nickp27** [ccxt/binance-trade-bot#224]
Hi there

I seem to have an error running the latest build in docker:

2021-03-22 18:04:59,976 - crypto_trading_logger - ERROR - Error while scouting...

Traceback (most recent call last):
File "/app/binance_trade_bot/scheduler.py", line 25, in _run_job
super()._run_job(job)
File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
ret = job.run()
File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
ret = self.job_func()
File "/app/binance_trade_bot/auto_trader.py", line 118, in scout
all_tickers = self.manager.get_all_market_tickers()
File "/app/binance_trade_bot/binance_api_manager.py", line 61, in get_all_market_tickers
return self.binance_client.get_all_tickers()
File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 437, in get_all_tickers
return self._get('ticker/price', version=self.PRIVATE_API_VERSION)

File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 237, in _get
return self._request_api('get', path, signed, version, **kwargs)

File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
return self._request(method, uri, signed, **kwargs)
File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 197, in _request
return self._handle_response()
File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.

**Comment by GrigorovskyA** [comment]
Just increase scout_sleep_time in user.cfg
It will be fixed after merge #211

**Comment by nickp27** [comment]
Thanks - i'll give that a go.

**Comment by alikazi88** [comment]
> Thanks - i'll give that a go.

Did it work ? @nickp27

**Comment by rel-s** [comment]
This is a known issue, and #211 should help indeed. In the meantime @GrigorovskyA 's advice is best, if you have further issues regarding this topic please open them in our Discord channel. Thanks!

**Comment by xioxu** [comment]
Hi, I changed its value to 300, "scout_sleep_time=300",  but useless, it not works!

**Comment by j-waters** [comment]
There are three solutions currently:

1. Reduce the number of enabled coins, ie remove coins from your `supported_coins_list` file and restart the bot
2. Modify the `BinanceAPIManager.get_fee()` method to only return `0.001`
3. Go back to commit 7e1f72c80d1e6ef05249baff865c1df6c2e1a095

**Comment by 77mena** [comment]
Readme
