### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mooksz** [ccxt/binance-trade-bot#258]
When trying to run the `python -m binance_trade_bot` command I get the following error:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "binance_trade_bot/backtest.py", line 18
    def __init__(self, manager: "MockBinanceManager"):  # pylint: disable=super-init-not-called
                              ^
SyntaxError: invalid syntax
```

**Comment by mooksz** [comment]
Solved it by using `python3 -m binance_trade_bot`. Totally new to python, so I'm a noob. Sorry :)
