### ISSUE TITLE
bot won't start

### ISSUE THREAD

**Issue by aplodismenty** [ccxt/binance-trade-bot#259]
2021-04-10 20:45:31,695 - crypto_trading_logger - INFO - Starting
Traceback (most recent call last):
  File "C:\Users\WarZ\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\WarZ\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Bots\binance-trade-bot\binance_trade_bot\__main__.py", line 5, in <module>
    main()
  File "C:\Bots\binance-trade-bot\binance_trade_bot\crypto_trading.py", line 16, in main
    config = Config()
  File "C:\Bots\binance-trade-bot\binance_trade_bot\config.py", line 30, in __init__
    self.BRIDGE_SYMBOL = os.environ.get("BRIDGE_SYMBOL") or config.get(USER_CFG_SECTION, "bridge")
  File "C:\Users\WarZ\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\WarZ\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'binance_user_config'

**Comment by MrEduar** [comment]
Could you give more details on how you solved the problem?

**Comment by Ahacad** [comment]
Hello I met the same problem, did you manage to solve it?

**Comment by mreduar** [comment]
> Hello I met the same problem, did you manage to solve it?

Check the name of your user.cfg and that it is correct

**Comment by Ahacad** [comment]
> > Hello I met the same problem, did you manage to solve it?
> 
> Check the name of your user.cfg and that it is correct

Thank you and now the program is successfully launched. The README is actually a bit misleading, I firstly thought that a `.user.cfg` was needed. :sweat_smile:

**Comment by alkhachatryan** [comment]
We just need to have a user.cfg file.

Docker compose create a folder instead of file :D
