### ISSUE TITLE
crypto_trading_logger - ERROR - Error while scouting...ent coin: TRXUSDT

### ISSUE THREAD

**Issue by Strenna** [ccxt/binance-trade-bot#262]
I would take te opportunity to thank you for sharing this bot!

I don't know if it's a real bug or am i doing something wrong, i've just registered a new Binance account, created api key and started to setup and test the bot.

My Binance account is without funds (guessing the errors are caused by this but still asking), i am just testing if everything work on my system since i have 3 different versions of Python (macOS) and then add funds to my account

First run i saw this:

> 2021-04-11 10:22:09,236 - crypto_trading_logger - INFO - Starting
2021-04-11 10:22:09,794 - crypto_trading_logger - INFO - Chosen strategy: default
2021-04-11 10:22:09,795 - crypto_trading_logger - INFO - Creating database schema if it doesn't already exist
2021-04-11 10:22:10,803 - crypto_trading_logger - INFO - Initializing <ADA> vs <ATOM>
2021-04-11 10:22:10,803 - crypto_trading_logger - INFO - Initializing <ADA> vs <BAT>
2021-04-11 10:22:10,803 - crypto_trading_logger - INFO - Initializing <ADA> vs <BTT>
2021-04-11 10:22:10,804 - crypto_trading_logger - INFO - Initializing <ADA> vs <DASH>
2021-04-11 10:22:10,804 - crypto_trading_logger - INFO - Initializing <ADA> vs <DOGE>
2021-04-11 10:22:10,804 - crypto_trading_logger - INFO - Initializing <ADA> vs <EOS>
2021-04-11 10:22:10,804 - crypto_trading_logger - INFO - Initializing <ADA> vs <ETC>
2021-04-11 10:22:10,804 - crypto_trading_logger - INFO - Initializing <ADA> vs <ICX>
2021-04-11 10:22:10,804 - crypto_trading_logger - INFO - Initializing <ADA> vs <IOTA>
2021-04-11 10:22:10,805 - crypto_trading_logger - INFO - Initializing <ADA> vs <NEO>
2021-04-11 10:22:10,805 - crypto_trading_logger - INFO - Initializing <ADA> vs <OMG>
2021-04-11 10:22:10,805 - crypto_trading_logger - INFO - Initializing <ADA> vs <ONT>
2021-04-11 10:22:10,805 - crypto_trading_logger - INFO - Initializing <ADA> vs <QTUM>
2021-04-11 10:22:10,805 - crypto_trading_logger - INFO - Initializing <ADA> vs <TRX>
2021-04-11 10:22:10,805 - crypto_trading_logger - INFO - Initializing <ADA> vs <VET>
2021-04-11 10:22:10,805 - crypto_trading_logger - INFO - Initializing <ADA> vs <XLM>
2021-04-11 10:22:10,805 - crypto_trading_logger - INFO - Initializing <ADA> vs <XMR>
2021-04-11 10:22:10,806 - crypto_trading_logger - INFO - Initializing <ATOM> vs <ADA>
2021-04-11 10:22:10,806 - crypto_trading_logger - INFO - Initializing <ATOM> vs <BAT>
2021-04-11 10:22:10,806 - crypto_trading_logger - INFO - Initializing <ATOM> vs <BTT>
2021-04-11 10:22:10,806 - crypto_trading_logger - INFO - Initializing <ATOM> vs <DASH>
2021-04-11 10:22:10,806 - crypto_trading_logger - INFO - Initializing <ATOM> vs <DOGE>
...
2021-04-11 10:22:10,847 - crypto_trading_logger - INFO - Initializing <XMR> vs <QTUM>
2021-04-11 10:22:10,847 - crypto_trading_logger - INFO - Initializing <XMR> vs <TRX>
2021-04-11 10:22:10,847 - crypto_trading_logger - INFO - Initializing <XMR> vs <VET>
2021-04-11 10:22:10,847 - crypto_trading_logger - INFO - Initializing <XMR> vs <XLM>
2021-04-11 10:22:10,867 - crypto_trading_logger - INFO - Setting initial coin to TRX
2021-04-11 10:22:10,965 - crypto_trading_logger - INFO - Purchasing <TRX> to begin trading
2021-04-11 10:22:13,803 - crypto_trading_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-04-11 10:22:13,803 - crypto_trading_logger - INFO - unsupported operand type(s) for *: 'NoneType' and 'int'
2021-04-11 10:22:14,610 - crypto_trading_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-04-11 10:22:15,727 - crypto_trading_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-04-11 10:22:16,547 - crypto_trading_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-04-11 10:22:17,776 - crypto_trading_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-04-11 10:22:18,567 - crypto_trading_logger - INFO - Failed to Buy/Sell. Trying Again.

Then i have stopped the bot since i was thinking it was because of lack of funds, then i tried again but now i get:

> 2021-04-11 10:47:06,767 - crypto_trading_logger - INFO - Starting
2021-04-11 10:47:07,197 - crypto_trading_logger - INFO - Chosen strategy: default
2021-04-11 10:47:07,198 - crypto_trading_logger - INFO - Creating database schema if it doesn't already exist
2021-04-11 10:47:14,771 - crypto_trading_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "/Users/strenna/Desktop/binance-trade-bot-master/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/Users/strenna/Library/Python/3.8/lib/python/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/Users/strenna/Library/Python/3.8/lib/python/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/Users/strenna/Desktop/binance-trade-bot-master/binance_trade_bot/strategies/default_strategy.py", line 40, in scout
    self._jump_to_best_coin(current_coin, current_coin_price, all_tickers)
  File "/Users/strenna/Desktop/binance-trade-bot-master/binance_trade_bot/auto_trader.py", line 128, in _jump_to_best_coin
    ratio_dict = self._get_ratios(coin, coin_price, all_tickers)
  File "/Users/strenna/Desktop/binance-trade-bot-master/binance_trade_bot/auto_trader.py", line 115, in _get_ratios
    transaction_fee = self.manager.get_fee(pair.from_coin, self.config.BRIDGE, True) + self.manager.get_fee(
  File "/Users/strenna/Desktop/binance-trade-bot-master/binance_trade_bot/binance_api_manager.py", line 48, in get_fee
    self._sell_quantity(origin_coin.symbol, target_coin.symbol)
  File "/Users/strenna/Desktop/binance-trade-bot-master/binance_trade_bot/binance_api_manager.py", line 206, in _sell_quantity
    return math.floor(origin_balance * 10 ** origin_tick) / float(10 ** origin_tick)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

Just asking if this error is caused by 0 funds or something else since i didn't get these errors at first run

**Comment by Strenna** [comment]
Solved, thats why my balance was 0.
