### ISSUE TITLE
not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by mushahidgillani** [ccxt/binance-trade-bot#263]
Traceback (most recent call last):
  File "binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File ".local/lib/python3.6/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File ".local/lib/python3.6/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "binance-trade-bot/binance_trade_bot/strategies/default_strategy.py", line 41, in scout
    self.bridge_scout()
  File "/home/mushahid/Documents/binance-trade-bot/binance_trade_bot/strategies/default_strategy.py", line 46, in bridge_scout
    current_coin.symbol, self.config.BRIDGE.symbol
TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by rel-s** [comment]
Maybe share some more information with us? Your config files seem to be the issue here...

**Comment by sagaratalatti** [comment]
I am having the same issue. I am python 3.9.4 on windows 10. Here's configuration:

### user.cfg
```
[binance_user_config]
api_key=LOL
api_secret_key=LOL
current_coin=BNB
bridge=USDT
tld=com
hourToKeepScoutHistory=1
scout_multiplier=5
scout_sleep_time=5
strategy=default
```

**Comment by Pekafu** [comment]
since this commit: [*Update trading logic to support cancel timeout order*](https://github.com/edeng23/binance-trade-bot/commit/b90cd274095a62a92b6c5cd9112b520c2e10f413#diff-11b4050e3ca21dccf33c4179d1d8f433439cf31bce93105a769d630f653c5f41) that part of the code should no longer be executed. 

Issue seems to be that there was no current_coin in the database which return None. If someone still wishes to use legacy code fix would be something like this: 
```
def bridge_scout(self):
        current_coin = self.db.get_current_coin()
        if current_coin is None:
             return
```
