### ISSUE TITLE
Switch python version from 3.8 to 3.7 in docker image

### ISSUE THREAD

**Issue by Tymec** [ccxt/binance-trade-bot#264]
When I've tried to deploy the docker image using the docker-compose file on my rpi4 with a 32-bit OS, both the binance_trader and binance_trader_api containers fail. 
I suspect that binance_trader_api container fails due to using python version 3.8 instead of 3.7 as I've got a similar issue on my Windows PC while using python 3.8.

docker version output:
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:19:30 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:17:16 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

binance_trader_api container output:
```
,
Error: class uri 'eventlet' invalid or not found: ,
,
[Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 12, in <module>,
    import eventlet,
  File "/usr/local/lib/python3.8/site-packages/eventlet/__init__.py", line 17, in <module>,
    from eventlet import convenience,
  File "/usr/local/lib/python3.8/site-packages/eventlet/convenience.py", line 4, in <module>,
    from eventlet import greenpool,
  File "/usr/local/lib/python3.8/site-packages/eventlet/greenpool.py", line 4, in <module>,
    from eventlet import queue,
  File "/usr/local/lib/python3.8/site-packages/eventlet/queue.py", line 49, in <module>,
    from eventlet.event import Event,
  File "/usr/local/lib/python3.8/site-packages/eventlet/event.py", line 3, in <module>,
    from eventlet import hubs,
  File "/usr/local/lib/python3.8/site-packages/eventlet/hubs/__init__.py", line 7, in <module>,
    from eventlet.support import greenlets as greenlet,
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/__init__.py", line 6, in <module>,
    from eventlet.support import greenlets,
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/greenlets.py", line 3, in <module>,
    import greenlet,
  File "/usr/local/lib/python3.8/site-packages/greenlet/__init__.py", line 29, in <module>,
    from ._greenlet import _C_API # pylint:disable=no-name-in-module,
ModuleNotFoundError: No module named 'greenlet._greenlet',
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 99, in load_class,
    mod = importlib.import_module('.'.join(components)),
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 14, in <module>,
    raise RuntimeError("eventlet worker requires eventlet 0.24.1 or higher"),
RuntimeError: eventlet worker requires eventlet 0.24.1 or higher,
],
,
```
binance_trader output:
```
/usr/local/bin/python: No module named binance_trade_bot,
```

**Comment by grittisemper** [comment]
@Tymec I have the same problem, how did you solve it?

**Comment by fazilmohamed00** [comment]
@Tymec I have the same problem, how did you solve it?
