### ISSUE TITLE
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

### ISSUE THREAD

**Issue by Shah-imran** [ccxt/binance-trade-bot#279]
When backtesting from (2021, 4, 1) to now I encountered this error.
```2021-04-16 02:15:27,281 - backtesting_logger - INFO - Scouting for best trades. Current ticker: VTHOUSDT
2021-04-16 02:15:27,319 - backtesting_logger - INFO - Scouting for best trades. Current ticker: VTHOUSDT
2021-04-16 02:15:27,343 - backtesting_logger - INFO - Fetching prices for WINBTC between 2021-04-03 08:40:00 and 04 Apr 2021 01:20:00
2021-04-16 02:15:28,155 - backtesting_logger - INFO - Fetching prices for VTHOBTC between 2021-04-03 08:40:00 and 04 Apr 2021 01:20:00
Traceback (most recent call last):
  File "backtest.py", line 8, in <module>
    btc_value = manager.collate_coins("BTC")
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\binance_trade_bot\backtest.py", line 130, in collate_coins
    price = self.get_market_ticker_price(coin + target_symbol)
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\binance_trade_bot\backtest.py", line 65, in get_market_ticker_price
    ticker_symbol, "1m", target_date, end_date, limit=1000
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\env\lib\site-packages\binance\client.py", line 794, in get_historical_klines
    first_valid_ts = self._get_earliest_valid_timestamp(symbol, interval)
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\env\lib\site-packages\binance\client.py", line 752, in _get_earliest_valid_timestamp
    endTime=None
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\env\lib\site-packages\binance\client.py", line 734, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\env\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\env\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\env\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "E:\Upwork\2021\trading_bot\binance-trade-bot\env\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.
```

**Comment by Blaklis** [comment]
Should be fixed by #275.

**Comment by hardkano** [comment]
I,m encountering the same error if i have either BTC or USDT in the supported coin list. it try to fetch USDTUSDT or BTCBTC. When i remove it it work flawlessly. I've update my local repos few hours ago.

**Comment by rel-s** [comment]
PR merged, closing.
