### ISSUE TITLE
BinanceAPIException: APIError(code=-1003): Way too much request weight used; IP banned until 1618636066762. Please use the websocket for live updates to avoid bans.

### ISSUE THREAD

**Issue by toanpv92hy** [ccxt/binance-trade-bot#283]
Traceback (most recent call last):
  File "/app/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/app/binance_trade_bot/strategies/default_strategy.py", line 17, in scout
    all_tickers = self.manager.get_all_market_tickers()
  File "/app/binance_trade_bot/binance_api_manager.py", line 70, in get_all_market_tickers
    return AllTickers(self.binance_client.get_all_tickers())
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 437, in get_all_tickers
    return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Way too much request weight used; IP banned until 1618636066762. Please use the websocket for live updates to avoid bans.

**Comment by j-waters** [comment]
#211

**Comment by rel-s** [comment]
We are aware of this, related to the websocket project. Closing for duplication.
