### ISSUE TITLE
exception occurred while following default strategy

### ISSUE THREAD

**Issue by sonuishaq67** [ccxt/binance-trade-bot#302]
Traceback (most recent call last):
  File "/home/toor/zoss/binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/home/toor/.local/lib/python3.9/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/home/toor/.local/lib/python3.9/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/home/toor/zoss/binance-trade-bot/binance_trade_bot/strategies/default_strategy.py", line 34, in scout
    self._jump_to_best_coin(current_coin, current_coin_price, all_tickers)
  File "/home/toor/zoss/binance-trade-bot/binance_trade_bot/auto_trader.py", line 140, in _jump_to_best_coin
    ratio_dict = self._get_ratios(coin, coin_price, all_tickers)
  File "/home/toor/zoss/binance-trade-bot/binance_trade_bot/auto_trader.py", line 127, in _get_ratios
    transaction_fee = self.manager.get_fee(pair.from_coin, self.config.BRIDGE, True) + self.manager.get_fee(
  File "/home/toor/zoss/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 49, in get_fee
    self._sell_quantity(origin_coin.symbol, target_coin.symbol)
  File "/home/toor/zoss/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 257, in _sell_quantity
    origin_balance = origin_balance or self.get_currency_balance(origin_symbol)
  File "/home/toor/zoss/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 85, in get_currency_balance
    for currency_balance in self.binance_client.get_account()["balances"]:
  File "/home/toor/.local/lib/python3.9/site-packages/binance/client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "/home/toor/.local/lib/python3.9/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/toor/.local/lib/python3.9/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/toor/.local/lib/python3.9/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/toor/.local/lib/python3.9/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.

**Comment by Han0nly** [comment]
A similar exception occurred to me. I think this is due to too frequent requests.
```
File "/home/ec2-user/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 61, in get_fee
    bnb_balance = self.get_currency_balance("BNB")
  File "/home/ec2-user/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 85, in get_currency_balance
    for currency_balance in self.binance_client.get_account()["balances"]:
  File "/home/ec2-user/.local/lib/python3.7/site-packages/binance/client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/binance/client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
