### ISSUE TITLE
i can't get to run the bot (i'm on windows )

### ISSUE THREAD

**Issue by yacinos95** [ccxt/binance-trade-bot#324]
File "C:\Users\habiba\Desktop\binance-trade-bot-master\binance_trade_bot\__main__.py", line 1, in <module>
    from .crypto_trading import main
ImportError: attempted relative import with no known parent package

**Comment by yacinos95** [comment]
i get this error when trying to start the bot

C:\Users\habiba>python -m binance_trade_bot
Traceback (most recent call last):
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\binance_trade_bot\__init__.py", line 1, in <module>
    from .backtest import backtest
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\binance_trade_bot\backtest.py", line 14, in <module>
    cache = SqliteDict("data/backtest_cache.db")
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlitedict.py", line 157, in __init__
    raise RuntimeError('Error! The directory does not exist, %s' % dirname)
RuntimeError: Error! The directory does not exist, data
