### ISSUE TITLE
I GET THIS ERROR WHEN TRYING TO START THE BOT

### ISSUE THREAD

**Issue by yacinos95** [ccxt/binance-trade-bot#325]
C:\Users\habiba>python -m binance_trade_bot
Traceback (most recent call last):
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\binance_trade_bot\__init__.py", line 1, in <module>
    from .backtest import backtest
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\binance_trade_bot\backtest.py", line 14, in <module>
    cache = SqliteDict("data/backtest_cache.db")
  File "C:\Users\habiba\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlitedict.py", line 157, in __init__
    raise RuntimeError('Error! The directory does not exist, %s' % dirname)
RuntimeError: Error! The directory does not exist, data

**Comment by rel-s** [comment]
Hi there, this is not a bug with the bot but rather an issue with your own setup. Please move this discussion to our Discord channel.
