### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'Coin'

### ISSUE THREAD

**Issue by MorganCl** [ccxt/binance-trade-bot#339]
Error while scouting...
Traceback (most recent call last):
  File "/home/pi/Documents/general_trader/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.7/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.7/dist-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/home/pi/Documents/general_trader/binance_trade_bot/strategies/multiple_coins_strategy.py", line 39, in scout
    f"{datetime.now()} - CONSOLE - INFO - I am scouting the best trades. "
TypeError: unsupported operand type(s) for +: &apos;NoneType&apos; and &apos;Coin&apos;

Please note, the '&apos;' refers to the " ' " symbol; but due to the conversion for telegram it is replace with that

This error message comes up several times and then stops, then comes  back again. Restarting 'sorta' solves it but it keeps coming back. 

Any Ideas?

**Comment by israelins85** [comment]
Same here: 

```
2021-05-19 14:31:44,500 - crypto_trading_logger - INFO - APIError(code=-2013): Order does not exist.
2021-05-19 14:31:54,140 - crypto_trading_logger - INFO - Bought ADA
2021-05-19 14:32:09,950 - crypto_trading_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "/Users/israelins/Documents/Programacao.nosync/3rd/binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/Users/israelins/Documents/Programacao.nosync/3rd/binance-trade-bot/binance_trade_bot/strategies/multiple_coins_strategy.py", line 40, in scout
    f"Current coin: {current_coin + self.config.BRIDGE} ",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'Coin'
```

**Comment by MasaiasuOse** [comment]
This is an error that occurs in the strategy.Do this fix in `strategies/multiple_coins_strategy.py`
replace : 

 ```
           print(
                f"{datetime.now()} - CONSOLE - INFO - I am scouting the best trades. "
                f"Current coin: {current_coin + self.config.BRIDGE} ",
                end="\r",
            )
```


with 

   

```
         print(
                f"{datetime.now()} - CONSOLE - INFO - I am scouting the best trades. "
                f"Current coin: {coin + self.config.BRIDGE} ",
                end="\r",
            )
```

**Comment by israelins85** [comment]
I changed strategy to default and back again to multiple_coins and resolved...
