### ISSUE TITLE
Binancewithdrawalexception: illegal characters found in parameter 'ip'

### ISSUE THREAD

**Issue by lrisley** [ccxt/binance-trade-bot#342]
error in line 2170 in get_trade_fee
not sure what it isn't getting.

**Comment by lrisley** [comment]
SO, I started my VPN and then ran the Bot and it ran just fine (sort of).

**Comment by joshkaspar** [comment]
I'm having the same issue and VPN did not make a difference. I made sure my current IP is added to the API. I also tried allowing any IP. Same error every time.
Here is the full error:
crypto_trading_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "C:\tools\binance-trade-bot\binance_trade_bot\scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python39\lib\site-packages\schedule\__init__.py", line 147, in _run_job
    ret = job.run()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python39\lib\site-packages\schedule\__init__.py", line 491, in run
    ret = self.job_func()
  File "C:\tools\binance-trade-bot\binance_trade_bot\strategies\default_strategy.py", line 34, in scout
    self._jump_to_best_coin(current_coin, current_coin_price, all_tickers)
  File "C:\tools\binance-trade-bot\binance_trade_bot\auto_trader.py", line 140, in _jump_to_best_coin
    ratio_dict = self._get_ratios(coin, coin_price, all_tickers)
  File "C:\tools\binance-trade-bot\binance_trade_bot\auto_trader.py", line 127, in _get_ratios
    transaction_fee = self.manager.get_fee(pair.from_coin, self.config.BRIDGE, True) + self.manager.get_fee(
  File "C:\tools\binance-trade-bot\binance_trade_bot\binance_api_manager.py", line 45, in get_fee
    base_fee = self.get_trade_fees()[origin_coin + target_coin]
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python39\lib\site-packages\cachetools\decorators.py", line 22, in wrapper
    v = func(*args, **kwargs)
  File "C:\tools\binance-trade-bot\binance_trade_bot\binance_api_manager.py", line 38, in get_trade_fees
    return {ticker["symbol"]: ticker["taker"] for ticker in self.binance_client.get_trade_fee()["tradeFee"]}
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 2302, in get_trade_fee
    raise BinanceWithdrawException(res['msg'])
binance.exceptions.BinanceWithdrawException: BinanceWithdrawException: Illegal characters found in parameter 'ip'; legal range is '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'.

**Comment by joshkaspar** [comment]
I disabled ipv6 and the error went away
