### ISSUE TITLE
How to limit interface request speed

### ISSUE THREAD

**Issue by xycfree** [ccxt/binance-trade-bot#354]
Traceback (most recent call last):
  File "/root/binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/root/binance-trade-bot/.env/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/root/binance-trade-bot/.env/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/root/binance-trade-bot/binance_trade_bot/auto_trader.py", line 185, in update_values
    balance = self.manager.get_currency_balance(coin.symbol)
  File "/root/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 99, in get_currency_balance
    for currency_balance in self.binance_client.get_account()["balances"]:
  File "/root/binance-trade-bot/.env/lib/python3.8/site-packages/binance/client.py", line 1822, in get_account
    return self._get('account', True, data=params)
  File "/root/binance-trade-bot/.env/lib/python3.8/site-packages/binance/client.py", line 292, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/root/binance-trade-bot/.env/lib/python3.8/site-packages/binance/client.py", line 242, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/root/binance-trade-bot/.env/lib/python3.8/site-packages/binance/client.py", line 237, in _request
    return self._handle_response()
  File "/root/binance-trade-bot/.env/lib/python3.8/site-packages/binance/client.py", line 285, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.

How to limit interface request speed？？

**Comment by rel-s** [comment]
Please see the config file, and for questions of this sort go to our Discord channel. The Github issues are for bug reports and discussions.
