### ISSUE TITLE
Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by lenovo1996** [ccxt/binance-trade-bot#396]
I got this error when run bot from docker.
How i can fix it?
```binance_trader    | Traceback (most recent call last):
binance_trader    |   File "/app/binance_trade_bot/scheduler.py", line 25, in _run_job
binance_trader    |     super()._run_job(job)
binance_trader    |   File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 172, in _run_job
binance_trader    |     ret = job.run()
binance_trader    |   File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 661, in run
binance_trader    |     ret = self.job_func()
binance_trader    |   File "/app/binance_trade_bot/strategies/default_strategy.py", line 32, in scout
binance_trader    |     self._jump_to_best_coin(current_coin, current_coin_price)
binance_trader    |   File "/app/binance_trade_bot/auto_trader.py", line 139, in _jump_to_best_coin
binance_trader    |     ratio_dict = self._get_ratios(coin, coin_price)
binance_trader    |   File "/app/binance_trade_bot/auto_trader.py", line 126, in _get_ratios
binance_trader    |     transaction_fee = self.manager.get_fee(pair.from_coin, self.config.BRIDGE, True) + self.manager.get_fee(
binance_trader    |   File "/app/binance_trade_bot/binance_api_manager.py", line 51, in get_fee
binance_trader    |     if not self.get_using_bnb_for_fees():
binance_trader    |   File "/usr/local/lib/python3.8/site-packages/cachetools/decorators.py", line 26, in wrapper
binance_trader    |     v = func(*args, **kwargs)
binance_trader    |   File "/app/binance_trade_bot/binance_api_manager.py", line 47, in get_using_bnb_for_fees
binance_trader    |     return self.binance_client.get_bnb_burn_spot_margin()["spotBNBBurn"]
binance_trader    |   File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 3080, in get_bnb_burn_spot_margin
binance_trader    |     return self._request_margin_api('get', 'bnbBurn', signed=True, data=params)
binance_trader    |   File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 275, in _request_margin_api
binance_trader    |     return self._request(method, uri, signed, **kwargs)
binance_trader    |   File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 260, in _request
binance_trader    |     return self._handle_response()
binance_trader    |   File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 313, in _handle_response
binance_trader    |     raise BinanceAPIException(self.response)
binance_trader    | binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request is outside of the recvWindow.
```

**Comment by Ivvanek** [comment]
Try to update your time clock.

**Comment by r4kh4t** [comment]
Have similar problem

**Comment by Thisuu** [comment]
For anyone having this issue on either Debian or Ubuntu, try these:

```
apt remove ntp ntpdate sntp
systemctl start systemd-timesyncd.service
```

Then check whether `NTP service: active` by
`timedatectl status`

**Comment by arcangelo7** [comment]
If you are on Windows, use https://www.timesynctool.com/. It fixed the problem for me.

**Comment by TimPushkin** [comment]
On Windows 10, pressing `Settings - Time & Language - Date & time - Synchronize your clock - Sync now` helped me.
