### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ArneNaessens** [ccxt/binance-trade-bot#412]
Bot suddenly stopped working with following error:

```
Traceback (most recent call last):
  File "C:\Users\arnenaessens\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\arnenaessens\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\arnenaessens\Documents\binance-trade-bot-master\binance_trade_bot\__main__.py", line 1, in <module>
    from .crypto_trading import main
ImportError: attempted relative import with no known parent package
```

Already redownloaded the bot, upgraded pip, reinstalled requirements.

**Comment by JohnathanEngine** [comment]
i have the same trouble
