### ISSUE TITLE
AttributeError: 'Select' object has no attribute 'scalar_subquery'

### ISSUE THREAD

**Issue by rujor** [ccxt/binance-trade-bot#420]
How can i fix this problem.  Thanks.

when i run python -m binance_trade_bot

the cosole show:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/app1/binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "/home/app1/binance_trade_bot/backtest.py", line 8, in <module>
    from .binance_api_manager import BinanceAPIManager
  File "/home/app1/binance_trade_bot/binance_api_manager.py", line 10, in <module>
    from .binance_stream_manager import BinanceCache, BinanceOrder, BinanceStreamManager, OrderGuard
  File "/home/app1/binance_trade_bot/binance_stream_manager.py", line 11, in <module>
    from .config import Config
  File "/home/app1/binance_trade_bot/config.py", line 5, in <module>
    from .models import Coin
  File "/home/app1/binance_trade_bot/models/__init__.py", line 5, in <module>
    from .pair import Pair
  File "/home/app1/binance_trade_bot/models/pair.py", line 8, in <module>
    class Pair(Base):
  File "/home/app1/binance_trade_bot/models/pair.py", line 22, in Pair
    select([func.count(Coin.symbol) == 2])
AttributeError: 'Select' object has no attribute 'scalar_subquery'

**Comment by rujor** [comment]
replace scalar_subquery with as_scalar()
