### ISSUE TITLE
Can't downloading packages

### ISSUE THREAD

**Issue by eladaspis** [ccxt/binance-trade-bot#423]
The error is the next message:
```
elad@ubuntu:~/Desktop/binance-trade-bot-5$ sudo pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

```

What can I do?
Thanks

**Comment by lisabbasil** [comment]
What python version?
`python --version`
