### ISSUE TITLE
Error while scouting...

### ISSUE THREAD

**Issue by shhhmel** [ccxt/binance-trade-bot#429]
```
2021-09-29 07:54:57,693 - crypto_trading_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/btb/binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/btb/binance-trade-bot/binance_trade_bot/strategies/multiple_coins_strategy.py", line 14, in scout
    current_coin = self.db.get_current_coin()
  File "/btb/binance-trade-bot/binance_trade_bot/database.py", line 111, in get_current_coin
    current_coin = session.query(CurrentCoin).order_by(CurrentCoin.datetime.desc()).first()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2750, in first
    return self.limit(1)._iter().first()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2834, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT current_coin_history.id AS current_coin_history_id, current_coin_history.coin_id AS current_coin_history_coin_id, current_coin_history.datetime AS current_coin_history_datetime 
FROM current_coin_history ORDER BY current_coin_history.datetime DESC
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

**Comment by lisabbasil** [comment]
Remove the lockfile from the database. That should be a file in your `data` directory.
