### ISSUE TITLE
get_market_ticker_price() returning NoneType

### ISSUE THREAD

**Issue by alvaromarfer** [ccxt/binance-trade-bot#44]
This is the error I'm getting. I just added USDT to the current coins
```
Traceback (most recent call last):
  File "crypto_trading.py", line 349, in <module>
    main()
  File "crypto_trading.py", line 338, in main
    initialize_trade_thresholds(client)
  File "crypto_trading.py", line 304, in initialize_trade_thresholds
    float(get_market_ticker_price(client, coin + 'USDT'))
TypeError: float() argument must be a string or a number, not 'NoneType'

```

**Comment by edeng23** [comment]
Do you mean that you added USDT to your supported coin list?

**Comment by alvaromarfer** [comment]
Yes, sorry. That's it
`supported_coin_list = [u'XLM', u'TRX', u'ICX', u'EOS', u'IOTA', u'ONT', u'QTUM', u'ETC', u'ADA', u'XMR', u'DASH', u'NEO', u'ATOM', u'DOGE', u'VET', u'BAT', u'OMG', u'BTT', u'USDT']`

**Comment by edeng23** [comment]
Yes, you can't have Tether (USDT) in your supported coin list because it is used as the bot's bridge currency. Besides, it doesn't really make sense to add Tether to the list because of its constant value. 
Remove it from the list and the problem should be fixed :)

**Comment by alvaromarfer** [comment]
Oooh okay!
But what if the coin I have is UDT? Should I change it for another one to make this bot work?

**Comment by edeng23** [comment]
Yes, pick any other coin from your list.
