### ISSUE TITLE
backtest.py problem

### ISSUE THREAD

**Issue by furkanbey01** [ccxt/binance-trade-bot#447]
**What am I doing wrong ?**

====== C:\Users\usr1\Desktop\binance-trade-bot-master\backtest.py =====
2021-11-18 13:25:08,508 - backtesting_logger - INFO - Fetching prices for ADAUSDT between 2021-01-01 00:00:00 and 01 Jan 2021 16:40:00
Traceback (most recent call last):
  File "C:\Users\usr1\Desktop\binance-trade-bot-master\backtest.py", line 7, in <module>
    for manager in backtest(datetime(2021, 1, 1), datetime.now()):
  File "C:\Users\usr1\Desktop\binance-trade-bot-master\binance_trade_bot\backtest.py", line 172, in backtest
    manager.buy_alt(starting_coin, config.BRIDGE)
  File "C:\Users\usr1\Desktop\binance-trade-bot-master\binance_trade_bot\backtest.py", line 76, in buy_alt
    from_coin_price = self.get_ticker_price(origin_symbol + target_symbol)
  File "C:\Users\usr1\Desktop\binance-trade-bot-master\binance_trade_bot\backtest.py", line 55, in get_ticker_price
    for result in self.binance_client.get_historical_klines(
  File "C:\Users\usr1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\binance\client.py", line 932, in get_historical_klines
    return self._historical_klines(symbol, interval, start_str, end_str=end_str, limit=limit, klines_type=klines_type)
  File "C:\Users\usr1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\binance\client.py", line 966, in _historical_klines
    start_ts = convert_ts_str(start_str)
  File "C:\Users\usr1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\binance\helpers.py", line 72, in convert_ts_str
    return date_to_milliseconds(ts_str)
  File "C:\Users\usr1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\binance\helpers.py", line 25, in date_to_milliseconds
    if d.tzinfo is None or d.tzinfo.utcoffset(d) is None:
AttributeError: 'NoneType' object has no attribute 'tzinfo'

**Comment by ghostnetrn** [comment]
Install Visual Studio : https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=17
Please install the default package and all those options:
![image](https://user-images.githubusercontent.com/54438080/149108027-f94a7ab5-b361-4fcd-9b54-d84e023f5315.png)
