### ISSUE TITLE
Tried to SET current coin to XVG, gives following error 

### ISSUE THREAD

**Issue by GrzegorzKarczewski** [ccxt/binance-trade-bot#48]
2021-02-13 16:37:04,034 - crypto_trader_logger - INFO - Started
2021-02-13 16:37:04,960 - crypto_trader_logger - INFO - Initializing XLM vs XLM
2021-02-13 16:37:05,278 - crypto_trader_logger - INFO - Initializing XLM vs TRX
2021-02-13 16:37:05,694 - crypto_trader_logger - INFO - Initializing XLM vs ICX
2021-02-13 16:37:06,020 - crypto_trader_logger - INFO - Initializing XLM vs EOS
2021-02-13 16:37:06,346 - crypto_trader_logger - INFO - Initializing XLM vs IOTA
2021-02-13 16:37:06,694 - crypto_trader_logger - INFO - Initializing XLM vs ONT
2021-02-13 16:37:08,061 - crypto_trader_logger - INFO - Initializing XLM vs QTUM
2021-02-13 16:37:08,406 - crypto_trader_logger - INFO - Initializing XLM vs ETC
2021-02-13 16:37:08,846 - crypto_trader_logger - INFO - Initializing XLM vs XVG
Traceback (most recent call last):
  File "crypto_trading.py", line 362, in <module>
    main()
  File "crypto_trading.py", line 351, in main
    initialize_trade_thresholds(client)
  File "crypto_trading.py", line 317, in initialize_trade_thresholds
    float(get_market_ticker_price(client, coin + 'USDT'))
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by rayanfer32** [comment]
Your issue is solved here: 

https://github.com/edeng23/binance-trade-bot/issues/44

**Comment by edeng23** [comment]
The pair XVG/USDT does not exist on Binance.
