### ISSUE TITLE
WARNING:apprise:Failed to send Telegram notification to *******: Bad Request: message is too long, error=400.

### ISSUE THREAD

**Issue by Axelfoley85** [ccxt/binance-trade-bot#492]
I think there was bad weather in my cloud.

Anyhow the appraise notfifier should truncan messages to notify the user.
```
2022-04-09 00:01:37,184 - crypto_trading_logger - INFO - Bought ADA
2022-04-09 02:03:29.910263 - CONSOLE - INFO - I am scouting the best trades. C2022-04-09 02:05:16,986 - crypto_trading_logger - ERROR - Error while scout
ing...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)   
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/app/binance_trade_bot/strategies/multiple_coins_strategy.py", line 43, in scout
    self._jump_to_best_coin(coin, coin_price)
  File "/app/binance_trade_bot/auto_trader.py", line 145, in _jump_to_best_coin
    ratio_dict = self._get_ratios(coin, coin_price)
  File "/app/binance_trade_bot/auto_trader.py", line 127, in _get_ratios
    from_fee = self.manager.get_fee(pair.from_coin, self.config.BRIDGE, True)
  File "/app/binance_trade_bot/binance_api_manager.py", line 51, in get_fee
    if not self.get_using_bnb_for_fees():
  File "/usr/local/lib/python3.8/site-packages/cachetools/decorators.py", line 26, in wrapper
    v = func(*args, **kwargs)
  File "/app/binance_trade_bot/binance_api_manager.py", line 47, in get_using_bnb_for_fees
    return self.binance_client.get_bnb_burn_spot_margin()["spotBNBBurn"]
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 3131, in get_bnb_burn_spot_margin
    return self._request_margin_api('get', 'bnbBurn', signed=True, data=params)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 364, in _request_margin_api
    return self._request(method, uri, signed, **kwargs)  
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 314, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

WARNING:apprise:Failed to send Telegram notification to *************: Bad Request: message is too long, error=400.
2022-04-09 11:02:45.973172 - CONSOLE - INFO - I am scouting the best trades. CurrWARNING:root:BinanceWebSocketApiManager._frequent_checks() - High CPU usage since 5 seconds: 100.0
2022-04-10 02:36:06.136555 - CONSOLE - INFO - I am scouti
2022-04-10 02:38:12,588 - crypto_trading_logger - INFO - Will be jumping from [ADA] to ONT
```

**Comment by Axelfoley85** [comment]
#### Solutions I see:
- truncate long messages
- send short additional message on errors
