### ISSUE TITLE
weird "Stop iteration error" out of nowhere 

### ISSUE THREAD

**Issue by shohart** [ccxt/binance-trade-bot#518]
So my bot was running fine for about 10 days, and suddenly I got this error.
```
Traceback (most recent call last):
  File "/home/ubuntu/trading-bot/binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/home/ubuntu/trading-bot/binance-trade-bot/binance_trade_bot/strategies/multiple_coins_strategy.py", line 28, in scout
    min_notional = self.manager.get_min_notional(coin.symbol, self.config.BRIDGE.symbol)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/cachetools/decorators.py", line 26, in wrapper
    v = func(*args, **kwargs)
  File "/home/ubuntu/trading-bot/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 148, in get_min_notional
    return float(self.get_symbol_filter(origin_symbol, target_symbol, "MIN_NOTIONAL")["minNotional"])
  File "/home/ubuntu/trading-bot/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 133, in get_symbol_filter
    return next(
StopIteration
```
Some error while fetching current coin value from binance?

**Comment by CoooWeee** [comment]
I have the same issue.

**Comment by shohart** [comment]
seems that some changes were implemented by binance and thus bot can not fetch pair values...

**Comment by lorvent** [comment]
wow...thanks for the confirmation.

i rebooted vps and did many other tricks only to find out it doesn't fix the problem.

hope devs implement fix soon

**Comment by tony77682** [comment]
I'm using a fork of the bot, and it's the binance_api_manager.py file that has been fixed.  if that can help

**Comment by lorvent** [comment]
> I'm using a fork of the bot, and it's the binance-api-manager.py file that has been fixed. if that can help

which fork?

**Comment by tony77682** [comment]
https://github.com/MasaiasuOse/binance-trade-bot

**Comment by lorvent** [comment]
> https://github.com/MasaiasuOse/binance-trade-bot

Thank you.... that fix fixed it.

**Comment by shohart** [comment]
> https://github.com/MasaiasuOse/binance-trade-bot

fixed
