### ISSUE TITLE
Trouble at switching to a new coin

### ISSUE THREAD

**Issue by NeoEraser** [ccxt/binance-trade-bot#520]
Everything was fine, it worked for more than six months, but at one fine moment it stopped working with the following error.

> 
crypto_trading_logger - INFO - Will be jumping from [ONT] to XLM
crypto_trading_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "C:\binance-trade-bot-master\binance_trade_bot\scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "C:\binance-trade-bot-master\binance_trade_bot\strategies\default_strategy.py", line 32, in scout
    self._jump_to_best_coin(current_coin, current_coin_price)
  File "C:\binance-trade-bot-master\binance_trade_bot\auto_trader.py", line 154, in _jump_to_best_coin
    self.transaction_through_bridge(best_pair)
  File "C:\binance-trade-bot-master\binance_trade_bot\auto_trader.py", line 31, in transaction_through_bridge
    if balance and balance * from_coin_price > self.manager.get_min_notional(
  File "C:\Users\k.prohoda\AppData\Local\Programs\Python\Python310\lib\site-packages\cachetools\decorators.py", line 26, in wrapper
    v = func(*args, **kwargs)
  File "C:\binance-trade-bot-master\binance_trade_bot\binance_api_manager.py", line 148, in get_min_notional
    return float(self.get_symbol_filter(origin_symbol, target_symbol, "MIN_NOTIONAL")["minNotional"])
  File "C:\binance-trade-bot-master\binance_trade_bot\binance_api_manager.py", line 133, in get_symbol_filter
    return next(
StopIteration

**Comment by tony77682** [comment]
binance changed something the bot doesn't like
for the moment I switched to a fork of the bot which has been updated:
https://github.com/MasaiasuOse/binance-trade-bot

**Comment by NeoEraser** [comment]
> binance changed something the bot doesn't like for the moment I switched to a fork of the bot which has been updated: https://github.com/MasaiasuOse/binance-trade-bot

Thx

**Comment by NeoEraser** [comment]
\binance_trade_bot\binance_api_manager.py
[-]        return float(self.get_symbol_filter(origin_symbol, target_symbol, "MIN_NOTIONAL")["minNotional"])
[+]      return float(self.get_symbol_filter(origin_symbol, target_symbol, "NOTIONAL")["minNotional"])
