### ISSUE TITLE
ImportError: cannot import name 'StreamManagerWorker' from 'binance_trade_bot.binance_stream_manager'

### ISSUE THREAD

**Issue by discoroveryx** [ccxt/binance-trade-bot#521]
`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/disc/trade_bot_env/binance-trade-bot/binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "/home/disc/trade_bot_env/binance-trade-bot/binance_trade_bot/backtest.py", line 8, in <module>
    from .binance_api_manager import BinanceAPIManager
  File "/home/disc/trade_bot_env/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 18, in <module>
    from .binance_stream_manager import (
ImportError: cannot import name 'StreamManagerWorker' from 'binance_trade_bot.binance_stream_manager' (/home/disc/trade_bot_env/binance-trade-bot/binance_trade_bot/binance_stream_manager.py)
`

**Comment by apurvns** [comment]
How to resolve this issue ?

**Comment by pookdeveloper** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/3384734/235341779-0b2a8a4a-e16c-465c-b0e0-2f454c64098d.png)

**Comment by Haruqun** [comment]
Same error.

**Comment by zhouwuchang** [comment]
same error

**Comment by Gimsza** [comment]
Why?
