### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by qpqqq** [ccxt/binance-trade-bot#522]
Hi,
After installing requirements using `pip install -r requirements.txt` and configuring `user.cfg` i tried to run by this command `python3 -m binance_trade_bot` i am getting this error ;

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ammura/bb/binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "/home/ammura/bb/binance_trade_bot/backtest.py", line 8, in <module>
    from .binance_api_manager import BinanceAPIManager
  File "/home/ammura/bb/binance_trade_bot/binance_api_manager.py", line 18, in <module>
    from .binance_stream_manager import (
ImportError: cannot import name 'StreamManagerWorker' from 'binance_trade_bot.binance_stream_manager' (/home/ammura/bb/binance_trade_bot/binance_stream_manager.py)`

**Comment by discoroveryx** [comment]
have the same problem

**Comment by qpqqq** [comment]
@fbradyirl , already pulled last commit

**Comment by apurvns** [comment]
Same issue here

**Comment by discoroveryx** [comment]
it still does not work
