### ISSUE TITLE
docker-compose up  run error

### ISSUE THREAD

**Issue by QGB** [ccxt/binance-trade-bot#530]
```
sqlitebrowser     | Obt-Message: Xinerama extension is not present on the server
binance_trader_api | [2023-05-20 13:38:06 +0000] [1] [INFO] Starting gunicorn 20.1.0
binance_trader_api | [2023-05-20 13:38:06 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2023-05-20 13:38:06 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2023-05-20 13:38:06 +0000] [3] [INFO] Booting worker with pid: 3
binance_trader    | 2023-05-20 13:38:08,803 - crypto_trading_logger - INFO - Starting
binance_trader    | Traceback (most recent call last):
binance_trader    |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
binance_trader    |     return _run_code(code, main_globals, None,
binance_trader    |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
binance_trader    |     exec(code, run_globals)
binance_trader    |   File "/app/binance_trade_bot/__main__.py", line 5, in <module>
binance_trader    |     main()
binance_trader    |   File "/app/binance_trade_bot/crypto_trading.py", line 16, in main
binance_trader    |     config = Config()
binance_trader    |   File "/app/binance_trade_bot/config.py", line 34, in __init__
binance_trader    |     self.BRIDGE_SYMBOL = os.environ.get("BRIDGE_SYMBOL") or config.get(USER_CFG_SECTION, "bridge")
binance_trader    |   File "/usr/local/lib/python3.8/configparser.py", line 781, in get
binance_trader    |     d = self._unify_values(section, vars)
binance_trader    |   File "/usr/local/lib/python3.8/configparser.py", line 1149, in _unify_values
binance_trader    |     raise NoSectionError(section) from None
binance_trader    | configparser.NoSectionError: No section: 'binance_user_config'
binance_trader_api | [2023-05-20 13:38:08 +0000] [3] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 134, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
binance_trader_api |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
binance_trader_api |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
binance_trader_api |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
binance_trader_api |   File "/app/binance_trade_bot/api_server.py", line 8, in <module>
binance_trader_api |     from flask_socketio import SocketIO, emit
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/flask_socketio/__init__.py", line 24, in <module>
binance_trader_api |     from werkzeug.serving import run_with_reloader
binance_trader_api | ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (/usr/local/lib/python3.8/site-packages/werkzeug/serving.py)
binance_trader_api | [2023-05-20 13:38:08 +0000] [3] [INFO] Worker exiting (pid: 3)
binance_trader exited with code 1
binance_trader_api | [2023-05-20 13:38:09 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2023-05-20 13:38:09 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader_api exited with code 3
sqlitebrowser     | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'

```

**Comment by maurimorero** [comment]
hey! @QGB I'm having the same issue, did you manage to solve it? Thank you!

**Comment by Fatihcill** [comment]
Hey! I have same issue too, did anyone solve it? 
thanks

**Comment by maurimorero** [comment]
Yeah! I override the docker-compose.yml to use the the Dockerfile instead of the custom image

**Comment by maxmanus96** [comment]
I also have the same issue even after using custom image

**Comment by max-menshenin** [comment]
> Yeah! I override the docker-compose.yml to use the the Dockerfile instead of the custom image

Can you say more how you fixed it?
What files you edited and how.

**Comment by wsdevprogrammer** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
iuyhnbv2048, @meafs, @filikos, @ccozkan, @frankmullenger, @yzkee, @CyberSecurityErial, @nschlemm, @melnikaite, @Archanoide, @asgeir-s, @ycaedes, @vulcangz, @theodesp, @Boyan-MILANOV, @y11en, @0xzh, @cgoehring3, @EvanPiro, @philipglazman
