### ISSUE TITLE
 Run error: "<frozen runpy>", line 189, in _run_module_as_main   File "<frozen runpy>", line 148, in _get_module_details   File "<frozen runpy>", line 112, in _get_module_details

### ISSUE THREAD

**Issue by arigatoexpress** [ccxt/binance-trade-bot#540]
File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/arigato/Downloads/binance-trade-bot-master/binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "/home/arigato/Downloads/binance-trade-bot-master/binance_trade_bot/backtest.py", line 8, in <module>
    from .binance_api_manager import BinanceAPIManager
  File "/home/arigato/Downloads/binance-trade-bot-master/binance_trade_bot/binance_api_manager.py", line 10, in <module>
    from .binance_stream_manager import BinanceCache, BinanceOrder, BinanceStreamManager, OrderGuard
  File "/home/arigato/Downloads/binance-trade-bot-master/binance_trade_bot/binance_stream_manager.py", line 9, in <module>
    from unicorn_binance_websocket_api import BinanceWebSocketApiManager
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/unicorn_binance_websocket_api/__init__.py", line 3, in <module>
    from unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager import BinanceWebSocketApiManager
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 40, in <module>
    from .unicorn_binance_websocket_api_restserver import BinanceWebSocketApiRestServer
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_restserver.py", line 36, in <module>
    from flask_restful import Resource
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 3, in <module>
    from flask import request, url_for, current_app
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask/app.py", line 27, in <module>
    from . import cli
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask/cli.py", line 17, in <module>
    from .helpers import get_debug_flag
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/werkzeug/urls.py)

**Comment by arigatoexpress** [comment]
pls hlp

**Comment by chchia** [comment]
i have exact same issues... help pls.

ps: just fixed by this
pip install --upgrade Flask

**Comment by chchia** [comment]
pip install --upgrade eventlet 
pip install --upgrade dnspython 

above 2 also required in my case.

**Comment by alkhachatryan** [comment]
As @chchia said

pip install --upgrade Flask
pip install --upgrade eventlet
pip install --upgrade dnspython

Helps!

**Comment by wyatt-wong** [comment]
It doesn't work for me.

```
wyattwong@MacBookPro ~ % python -m tkinter
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/wyattwong/.pyenv/versions/3.12.4/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

```
wyattwong@MacBookPro ~ % pyenv versions
  system
* 3.12.4 (set by /Users/wyattwong/.python-version)
  3.12.4/envs/venv
  venv --> /Users/wyattwong/.pyenv/versions/3.12.4/envs/venv
```
