### ISSUE TITLE
error running python -m binance-trade-bot

### ISSUE THREAD

**Issue by arigatoexpress** [ccxt/binance-trade-bot#544]
receiving these errors when trying to run- pls hlp
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/arigato/Downloads/binance-trade-bot-master/binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "/home/arigato/Downloads/binance-trade-bot-master/binance_trade_bot/backtest.py", line 8, in <module>
    from .binance_api_manager import BinanceAPIManager
  File "/home/arigato/Downloads/binance-trade-bot-master/binance_trade_bot/binance_api_manager.py", line 10, in <module>
    from .binance_stream_manager import BinanceCache, BinanceOrder, BinanceStreamManager, OrderGuard
  File "/home/arigato/Downloads/binance-trade-bot-master/binance_trade_bot/binance_stream_manager.py", line 9, in <module>
    from unicorn_binance_websocket_api import BinanceWebSocketApiManager
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/unicorn_binance_websocket_api/__init__.py", line 3, in <module>
    from unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager import BinanceWebSocketApiManager
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 40, in <module>
    from .unicorn_binance_websocket_api_restserver import BinanceWebSocketApiRestServer
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_restserver.py", line 36, in <module>
    from flask_restful import Resource
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 3, in <module>
    from flask import request, url_for, current_app
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask/app.py", line 27, in <module>
    from . import cli
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask/cli.py", line 17, in <module>
    from .helpers import get_debug_flag
  File "/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/arigato/Downloads/binance-trade-bot-master/.venv/lib/python3.11/site-packages/werkzeug/urls.py)

**Comment by arigatoexpress** [comment]
is this because I'm running in a virtual environment or something?

**Comment by ltoni90** [comment]
Had the same error. After adding the following line to requirements.txt and executing `pip install -r requirements.txt` it worked without any issues:
`Werkzeug==2.2.2` 

There seems to be an issue with the flask not specifying the dependency correctly:
[Stackoverflow](https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr
)

**Comment by alkhachatryan** [comment]
@ltoni90 it brings new error. Just tried on ubuntu 20

**Comment by tangzhifan** [comment]
I change the Werkzeug version to 2.0.3, and it works.
