### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by Milan-bst** [ccxt/binance-trade-bot#558]
I added the Werkzeug==2.2.2 to the requirements but after that I'm having issues with the eventlet library.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/milan/projects/binance-trade-bot/binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "/home/milan/projects/binance-trade-bot/binance_trade_bot/backtest.py", line 8, in <module>
    from .binance_api_manager import BinanceAPIManager
  File "/home/milan/projects/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 12, in <module>
    from .database import Database
  File "/home/milan/projects/binance-trade-bot/binance_trade_bot/database.py", line 8, in <module>
    from socketio import Client
  File "/home/milan/my_env/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/home/milan/my_env/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/home/milan/my_env/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/home/milan/my_env/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/milan/my_env/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/home/milan/my_env/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/home/milan/my_env/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/home/milan/my_env/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/home/milan/my_env/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'

**Comment by alkhachatryan** [comment]
Same crap.

**Comment by yoonxjoong** [comment]
I installed and ran Python 3.8.14 and there was no problem.

First, check your Python version and then check the Werkzeug version.

I hope this solves your problem. thanks

**Comment by hitiming** [comment]
pip install --upgrade eventlet

**Comment by Hassffw** [comment]
@hitiming +
 from collections.abc import MutableMapping 
change the import and class inheritation at 
/home/user/binance-trade-bot/lib/python3.11/site-packages/dns/namedict.py
