### ISSUE TITLE
first run error

### ISSUE THREAD

**Issue by creotip** [ccxt/binance-trade-bot#574]
Just git cloned, installed deps. configured the `user.cfg`

Then:
```
python -m binance_trade_bot
```

Output:
```
➜  binance-trade-bot git:(master) ✗ python -m binance_trade_bot

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/ruslanelishaev/Desktop/projects/binance-trade-bot/binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "/Users/ruslanelishaev/Desktop/projects/binance-trade-bot/binance_trade_bot/backtest.py", line 8, in <module>
    from .binance_api_manager import BinanceAPIManager
  File "/Users/ruslanelishaev/Desktop/projects/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 10, in <module>
    from .binance_stream_manager import BinanceCache, BinanceOrder, BinanceStreamManager, OrderGuard
  File "/Users/ruslanelishaev/Desktop/projects/binance-trade-bot/binance_trade_bot/binance_stream_manager.py", line 9, in <module>
    from unicorn_binance_websocket_api import BinanceWebSocketApiManager
  File "/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/unicorn_binance_websocket_api/__init__.py", line 3, in <module>
    from unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager import BinanceWebSocketApiManager
  File "/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 40, in <module>
    from .unicorn_binance_websocket_api_restserver import BinanceWebSocketApiRestServer
  File "/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_restserver.py", line 36, in <module>
    from flask_restful import Resource
  File "/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask_restful/__init__.py", line 3, in <module>
    from flask import request, url_for, current_app
  File "/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/app.py", line 27, in <module>
    from . import cli
  File "/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/cli.py", line 17, in <module>
    from .helpers import get_debug_flag
  File "/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/Users/ruslanelishaev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/werkzeug/urls.py)
```

**Comment by umairahmadh** [comment]
run these:
pip uninstall Werkzeug
pip install Werkzeug==2.0.3
