### ISSUE TITLE
ModuleNotFoundError: No module named 'cachetools'

### ISSUE THREAD

**Issue by gscagl** [ccxt/binance-trade-bot#576]
warnings.warn(
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/gscagl/Desktop/binance-trade-bot/binance_trade_bot/__init__.py", line 1, in <module>
    from .backtest import backtest
  File "/Users/gscagl/Desktop/binance-trade-bot/binance_trade_bot/backtest.py", line 8, in <module>
    from .binance_api_manager import BinanceAPIManager
  File "/Users/gscagl/Desktop/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 8, in <module>
    from cachetools import TTLCache, cached
ModuleNotFoundError: No module named 'cachetools'

What could i do?

**Comment by gscagl** [comment]
I've already uninstalled and installed cachetools, nothing
