### ISSUE TITLE
unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by TonyStark** [ccxt/binance-trade-bot#83]
python3 ./crypto_trading.py
```
2021-02-19 00:53:17,468 - crypto_trader_logger - INFO - Started
2021-02-19 01:43:25,735 - crypto_trader_logger - INFO - Initializing BTT vs ATOM
2021-02-19 01:43:25,735 - crypto_trader_logger - INFO - Initializing BTT vs DOGE
2021-02-19 01:43:25,735 - crypto_trader_logger - INFO - Initializing BTT vs VET
2021-02-19 01:43:25,736 - crypto_trader_logger - INFO - Initializing BTT vs BAT
2021-02-19 01:43:25,736 - crypto_trader_logger - INFO - Initializing BTT vs OMG
2021-02-19 01:43:25,736 - crypto_trader_logger - INFO - Initializing BTT vs BTT
2021-02-19 01:43:25,736 - crypto_trader_logger - INFO - Done initializing, generating file
2021-02-19 01:43:25,738 - crypto_trader_logger - INFO - Purchasing XLM to begin trading
Failed to Buy/Sell. Trying Again.
2021-02-19 01:43:27,261 - crypto_trader_logger - INFO - unsupported operand type(s) for *: 'NoneType' and 'int'
Failed to Buy/Sell. Trying Again.
Failed to Buy/Sell. Trying Again.
Failed to Buy/Sell. Trying Again.
Failed to Buy/Sell. Trying Again.
Failed to Buy/Sell. Trying Again.


```

**Comment by TonyStark** [comment]
after removing cloned repo
then again clone
and execute python3 ./crypto_trading.py i get this error


```
champion@pop-os:~/learn/binance-trade-bot$ python3 ./crypto_trading.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'bridge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./crypto_trading.py", line 46, in <module>
    BRIDGE = config.get(USER_CFG_SECTION, 'bridge')
  File "/usr/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'bridge' in section: 'binance_user_config'
champion@pop-os:~/learn/binance-trade-bot$ 

```

**Comment by j-waters** [comment]
As a side note I think we should handle crashes better, it would be nice if we could see the traceback of errors like these.

**Comment by TonyStark** [comment]
i think the issue raised because of 0.0000$ balance
after loading balance that error gone
