### ISSUE TITLE
configparser.NoOptionError: No option 'bridge' in section: 'binance_user_config'

### ISSUE THREAD

**Issue by mickaelsamak** [ccxt/binance-trade-bot#88]
File "/usr/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'bridge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crypto_trading.py", line 46, in <module>
    BRIDGE = config.get(USER_CFG_SECTION, 'bridge')
  File "/usr/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'bridge' in section: 'binance_user_config'

**Comment by mmpantazi** [comment]
You probably used your last user_config before the last update, check the user_config_example and follow that. It has a new variable called bridge

**Comment by rel-s** [comment]
Yep, that should fix it.

**Comment by mickaelsamak** [comment]
yes, that's it. thank you
